/**
 * Ambient module declaration for the Emscripten-generated PVAC WASM loader.
 * The actual file is pvac_server/build-wasm/pvac_wasm.mjs (generated by build-wasm.sh).
 */

declare module '*/pvac_wasm.mjs' {
  interface PvacEmscriptenModule {
    ccall(name: string, returnType: string | null, argTypes: string[], args: unknown[]): unknown
    getValue(ptr: number, type: string): number
    HEAPU8: Uint8Array
    _malloc(size: number): number
    _free(ptr: number): void
  }

  const PvacModule: (opts?: object) => Promise<PvacEmscriptenModule>
  export default PvacModule
}
